version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Zurich
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(python)

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
      time: "04:15"
      timezone: Europe/Zurich
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(web)

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Europe/Zurich
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(container)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:45"
      timezone: Europe/Zurich
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(actions)

